# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

jobs:
- job: RunThisCommand
  container: debian:latest
  variables:
    MY_NAME: Johnny
  steps:
    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package-lock.json'
        path: ~/.npm
    - bash: action-a/entrypoint.sh
  displayName: 'Run a one-line script'
