# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

jobs:
- job: RunThisCommand
  container: debian:9.5-slim
  variables:
    MY_NAME: Johnny
  steps:
    - bash: action-a/entrypoint.sh
  displayName: 'Run a one-line script'
